name: Auto Switch Profile README

on:
  schedule:
    - cron: "0 6 * * *"   # Every day at 06:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  switch-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main          # 👈 Always checkout main branch
          fetch-depth: 0

      - name: Detect weekday
        id: weekday
        run: echo "DAY=$(date +%u)" >> $GITHUB_ENV
        # %u → 1=Mon ... 7=Sun

      - name: Copy correct README
        run: |
          if [ "$DAY" -lt 6 ]; then
            cp README_minimal.md README.md
            echo "📝 Using Minimal README (Weekday)"
          else
            cp README_stylish.md README.md
            echo "🌈 Using Stylish README (Weekend)"
          fi

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
